apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanko
  namespace: hanko
  labels:
    app: hanko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hanko
  template:
    metadata:
      labels:
        app: hanko
    spec:
      containers:
        - name: hanko
          image: ghcr.io/teamhanko/hanko:main
          imagePullPolicy: IfNotPresent
          args:
            - serve
          ports:
            - containerPort: 8000
              name: public
            - containerPort: 8001
              name: private
          volumeMounts:
            - mountPath: /etc/config
              name: hanko-config
      initContainers:
        - name: hanko-migrate
          image: ghcr.io/teamhanko/hanko:main
          imagePullPolicy: IfNotPresent
          args:
            - migrate
            - up
          volumeMounts:
            - mountPath: /etc/config
              name: hanko-config
      volumes:
        - name: hanko-config
          configMap:
            name: hanko-config